### ISSUE TITLE
Need to test this scenario

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#1512] opened 2021-06-21 09:34 UTC
**Description:**
I have implemented a [chat application with Websocket](https://github.com/kalaiyarasiganeshalingam/chat-room-app) and tested it. But got the following error rarely when using multiple clients.

```
021-06-21 13:36:38,508] SEVERE {b7a.log.crash} - class ballerina.websocket.1_2_0-beta_1.Client_readTextMessageFrame cannot be cast to class kalaiyarasiganeshalingam.chat_room.0_1_0.mainFrame (ballerina.websocket.1_2_0-beta_1.Client_readTextMessageFrame and kalaiyarasiganeshalingam.chat_room.0_1_0.mainFrame are in unnamed module of loader 'app') 
java.lang.ClassCastException: class ballerina.websocket.1_2_0-beta_1.Client_readTextMessageFrame cannot be cast to class kalaiyarasiganeshalingam.chat_room.0_1_0.mainFrame (ballerina.websocket.1_2_0-beta_1.Client_readTextMessageFrame and kalaiyarasiganeshalingam.chat_room.0_1_0.mainFrame are in unnamed module of loader 'app')
	at kalaiyarasiganeshalingam.chat_room.0_1_0.chat_room.main(chat_room.bal:8)
	at kalaiyarasiganeshalingam.chat_room.0_1_0.$_init.$lambda$main$(chat_room)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
Check whether we have any chance to get this.

**Comment by Bhashinee** [comment] 2021-06-25 11:17
This can happen due to caching issues in Ballerina. Clearing the ballerina cache should work. Closing the issue from standard library as this is not a bug in WebSocket.

**Closed by Bhashinee** 2021-06-25 11:17 UTC
Labels: Team/PCP, Type/Bug, module/websocket
