### ISSUE TITLE
Returning Incorrect Values for GraphQL Introspection Queries

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#1377] opened 2021-05-18 06:58 UTC
**Description:**
1. Return incorrect values as the default values of resource function parameters.
2. Parameter type name is ```NULL``` when parameter type kind is ```NON_NULL```.

**Comment by ThisaruGuruge** [comment] 2021-05-18 07:59
> **Description:**
> 
> 1. Return incorrect values as the default values of resource function parameters.

Related to https://github.com/ballerina-platform/ballerina-lang/issues/30106

> 2. Parameter type name is `NULL` when parameter type kind is `NON_NULL`.

This is the expected behavior.

**Comment by ThisaruGuruge** [comment] 2021-05-25 09:13
The returning of the incorrect values for default values is actually a design limitation. We do not have a way to get the default value of an input parameter at the runtime. This is known at the time of implementation and as a temporary workaround, we used `zeroValue` of the input type as the default value, if an input parameter has a default value.

This does not affect the execution, since at the execution phase, since the default value is used from the runtime when we execute the function. The issue is the default value shown in the introspection queries is wrong.

Until the related lang issue (https://github.com/ballerina-platform/ballerina-lang/issues/30106) is fixed, this cannot be done. Therefore, removing the `Bug` label, and adding `Task` label.

**Comment by ThisaruGuruge** [comment] 2023-08-15 12:16
Closing as the remaining issue is tracked using #4720

**Closed by ThisaruGuruge** 2023-08-15 12:16 UTC
Labels: Type/Task, module/graphql, Team/PCM, Status/Blocked
