### ISSUE TITLE
Error cause not getting logged

### ISSUE THREAD

**Issue by arunans23** [ballerina-platform/ballerina-standard-library#1599] opened 2021-07-02 07:59 UTC
**Description:**

I am running the below Ballerina program. I am throwing error in functions and logging the error it in the main function. 

```
import ballerina/io;
import ballerina/log;

public function main() {
    error|string helloWorld = getHello();
    if (helloWorld is error) {
        log:printError("Error received", helloWorld);
        return;
    }
    io:println("Hello Ballerina!");
}

function getHello() returns string|error {
    error|string world = getWorld();
    if (world is error) {
        return error("Hello not found", world);
    }
    return world;
}

function getWorld() returns string|error {
    return error("World not found");
}
```

The above program prints the following line.
`time = 2021-07-02T13:21:21.925+05:30 level = ERROR module = "" message = "Error received" error = "Hello not found"`.

The error message "World not found" is not printed here. Is this the intended behavior or is it a bug?

**Steps to reproduce:**

Run the provided code.

**Affected Versions:**

SL Beta 1

**Comment by madushajg** [comment] 2021-07-02 08:34
Related to: https://github.com/ballerina-platform/ballerina-lang/issues/26679

**Comment by rdhananjaya** [comment] 2021-07-02 09:40
> Could be related to: [ballerina-platform/ballerina-lang#26679](https://github.com/ballerina-platform/ballerina-lang/issues/26679)

This issue fixed the toString implementation to print the error causes, the log issue probably needs to be fixed from `ballerina/log` module.

**Comment by MadhukaHarith92** [comment] 2021-07-08 04:17
This is not a bug. The `log` module prints the error "message" but does not print the error "cause" which is the agreed-upon behavior ATM.

**Comment by MadhukaHarith92** [comment] 2021-09-30 12:43
Closing since this is the accepted behavior ATM. 
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1959

**Closed by MadhukaHarith92** 2021-09-30 12:43 UTC
Labels: Points/2, Priority/High, Type/Improvement, module/log, Team/DIU
