### ISSUE TITLE
Intermittent test failure with `Remote host closed the connection before initiating inbound response` error

### ISSUE THREAD

**Issue by sachiniSam** [ballerina-platform/ballerina-standard-library#2438] opened 2021-06-23 06:59 UTC
**Description:**
Observed an intermittent test failure for the following scenario. 
There is a mock server which runs on the port (9093) and test cases were written based on the mock. And there is a separate test to check the readiness of above mentioned mock server by doing a tcp-dial. (the same port is used for the tcp-check as well)

```
isolated function tcpDialCheck(string address, int port, decimal timeout) returns int | error {
    tcp:Client socketClient = check new(address, port, timeout = timeout);
    check socketClient->close();
    return http:STATUS_OK;
}
```
Tests were intermittently failing with the error ` Remote host closed the connection before initiating inbound response` 

**Steps to reproduce:**

**Affected Versions:**
slbeta1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Bhashinee** [comment] 2021-12-06 04:28
Tested locally on Ballerina Swan Lake Beta 4. Seems the issue is fixed as it couldn't be reproduced. Hence closing the issue.

**Closed by Bhashinee** 2021-12-06 04:28 UTC
Labels: Type/Bug, module/tcp
