### ISSUE TITLE
Getting "client method invocation failed: invalid inbound request parameter" when calling the globally defined  http client

### ISSUE THREAD

**Issue by IsuruBoyagane15** [ballerina-platform/ballerina-standard-library#1917] opened 2021-09-16 04:15 UTC
**Description:**

I was developing a Ballerina service that have a resource function which calls external API endpoints (APIM, Github, IS, BC) while handling the request.

For one request of this resource function, the request handler function calls an APIM endpoint, IS endpoint, 3 Github endpoints, 2 BC endpoints.

I have used [globally defined](githubClient) http clients to call these endpoints in request handler functions.

However I observed the following behavior.

- A request (r1) to the developed service resource function will be served as expected.
- A subsequent request(r2) with the **same params** will give the `client method invocation failed: invalid inbound request parameter`. This http error for r2 will be given when calling the first (out of 3) Github API in the request handlers flow of r2.
- Subsequent requests with the same params as r1 and r2 will also give `client method invocation failed: invalid inbound request parameter` error.
- If a request (r5) with **different param** than r1 and r2 is made, it will be served successfully.
- However if a request (r6) with same params as r1 and r2 is made after the r5, r6 will also give the mentioned error.

As a workaround I have defined a http client for Github in the handler function level and passed as a parameter to the subsequent functions that are calling the Github APIs. In that case the subsequent requests with same params will be served by the service as expected.

Can we figure out why the globally defined http client is not working as expected.

**Affected Versions:**
SL Beta2

**OS, DB, other environment details and versions:**
Ubuntu 20.04.2 LTS (Focal Fossa)

**Suggested Assignees (optional):**
@shafreenAnfar

**Comment by chamil321** [comment] 2021-09-21 04:48
Duplicate of https://github.com/ballerina-platform/ballerina-standard-library/issues/1898

**Closed** 2021-09-23 06:03 UTC
Labels: Priority/High, Type/Bug, module/http, Team/PCP
