### ISSUE TITLE
Deprecation annotation not working without deprecation reason

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-standard-library#3322] opened 2022-09-07 07:59 UTC
**Description:**
According to graphql spec depreciation reason is optional for `@depricated` directive. 
Deprecation annotation not working without deprecation reason. 

**Steps to reproduce:**
```ballerina
import ballerina/graphql;

@graphql:ServiceConfig{
    cors: {
        allowOrigins: ["*"]
    },
    graphiql: {
        enabled: true
    }
}
service /a on new graphql:Listener(9000) {
    // not working
    @deprecated
    resource function get greet() returns string {
        return "hi";
    }

    // but this works
    # # Deprecated
    @deprecated
    resource function get greet2() returns string {
         return "hi";
     }
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by DimuthuMadushan** [comment] 2022-09-09 05:03
```ballerina
# # Deprecated
@deprecated
resource function get greet2() returns string {
     return "hi";
}
```
I think this is the correct way to use the `@deprecated` directive without a reason according to the [spec](https://github.com/ballerina-platform/module-ballerina-graphql/blob/master/docs/spec/spec.md#53-deprecated). Even if we use `deprecated` directive like this, It's not showing as a deprecated field in `GraphiQL` client. But it works in `Playground`. Seems like a bug in GraphiQL client.

Consider the following:
```ballerina
service /a on new graphql:Listener(9000) {
    # # Deprecated
    # please use the `greet2`
    @deprecated
    resource function get greet() returns string {
        return "hi";
    }

    # # Deprecated
    @deprecated
    resource function get greet2() returns string {
         return "hi";
     }
}
```
In GraphiQL:
![Screenshot from 2022-09-09 10-26-29](https://user-images.githubusercontent.com/35717653/189275197-43b51d0e-192c-48b1-81eb-27bf9d5d8060.png)

In Playground:
![Screenshot from 2022-09-09 10-26-39](https://user-images.githubusercontent.com/35717653/189275308-a1d59be1-a2fc-476e-bc52-45a7cbeadeaf.png)

**Comment by ThisaruGuruge** [comment] 2022-09-13 05:06
> It seems this is the correct way to use the @deprecated directive without a reason according to the spec. @ThisaruGuruge can you confirm this?

Consider this:
```ballerina
@deprecated
resource function get greet() returns string {
    return "hi";
}
```

I think the Ballerina language does not support deprecating without the doc comment like this. The way is the one @DimuthuMadushan mentioned. 

But I think we should be able to mark it as deprecated without the reason. No point in defining the doc comment, if we don't want to add a reason. @MaryamZi any thoughts?

> BTW, Even if we use deprecated directive like this, It's not showing as a deprecated field in GraphiQL client. But it works in Playground. Seems like a bug in GraphiQL client.

Yes, this might be a bug in GraphiQL. Shall we check this with them?

**Comment by ThisaruGuruge** [comment] 2022-09-13 07:28
Checked this again. It seems like there's no issue form the lang or the GraphQL package in Ballerina. Even when we don't have a deprecation documentation, the Ballerina compiler issues a warning, but still works as expected.

The introspection query works as expected and returns the field as deprecated, even though we don't have a deprecation reason. 

I think the issue is with the client tools where they do not identify fields without deprecation reason as deprecated. Let's check this with the tooling communities. Closing the issue since this isn't a bug in our side.

**Closed by ThisaruGuruge** 2022-09-13 07:28 UTC
Labels: Type/Bug, module/graphql, Team/PCM, Reason/Invalid
