### ISSUE TITLE
[Persist] Optional time types do not work

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#4078] opened 2023-02-13 07:41 UTC
**Description:**
When we try to persist a record containing an optional time type, the following error occurs
```
The field 'dateTypeOptional' of type  cannot be mapped to the column 'dateTypeOptional' of SQL type 'DATE'

```

**Steps to reproduce:**
```ballerina
type OptionalTimeTypes record {|
    readonly int id;
    time:Date? dateTypeOptional;
    time:TimeOfDay? timeOfDayTypeOptional;
    time:Utc? utcTypeOptional;
    time:Civil? civilTypeOptional;
|};
```

When it is attempted to persist a record of type `OptionalTimeTypes` we get the above error.

```ballerina
public function main() returns error? {
   OptionalTimeTypes insert = {
        id: 5,
        dateTypeOptional: {year: 1993, month: 11, day: 3},
        timeOfDayTypeOptional: {hour: 12, minute: 32, second: 34},
        civilTypeOptional: {year: 1993, month: 11, day: 3, hour: 12, minute: 32, second: 34},
        utcTypeOptional: time:utcNow()
    };

   TestEntitiesClient teClient = check new();
    int[] ids = check teClient->/alltypes.post([insert]);
}
```

**Comment by kalaiyarasiganeshalingam** [comment] 2023-02-27 09:13
I couldn't reproduce the error with the latest tools. It is working as expected. Hence, closing this issue.

**Closed by kalaiyarasiganeshalingam** 2023-02-27 09:13 UTC
Labels: Type/Bug, module/sql, Team/DIU, module/persist
