### ISSUE TITLE
Update dataloader proposal with dispatching approaches

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-standard-library#4192] opened 2023-03-13 09:39 UTC
**Description:**
$Subject

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment] 2023-04-24 18:22
Closing this as the issue is no longer valid.

**Closed by ThisaruGuruge** 2023-04-24 18:22 UTC
Labels: Points/1, Type/Task, module/graphql, Team/PCM
