### ISSUE TITLE
Java null point exception throws when using JDBC module

### ISSUE THREAD

**Issue by indrarajwso2** [ballerina-platform/ballerina-standard-library#1982] opened 2021-09-29 18:33 UTC
**Description:**
Used ballerina JDBC module to connect remote DB and call stored procedure. After running function returns a java null pointer exception.

Ballerina ver - beta 2

error: java.lang.NullPointerException
        at ballerinax.java.jdbc.0_6_0-beta_2.Client:call(client.bal:94)
           user_search:getInternalUserData(user_search.bal:491)
           $value$$anonType$_0:$post$searchClientData(user_search.bal:95)

**Comment by kaneeldias** [comment] 2021-10-06 06:12
Issue was due to `dbClient->call()` being called without specifying the expected return record types for a procedure which returns a result set.

Intended behaviour is to generate a default record using the retrieved column names.  

Fixed in https://github.com/ballerina-platform/module-ballerina-sql/pull/398

**Closed** 2021-10-06 08:51 UTC
Labels: Points/3, Type/Bug, module/sql, Team/DIU
