### ISSUE TITLE
__detach() and __gracefulStop() are not worked properly in the HTTP listener

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#499] opened 2020-09-09 05:48 UTC
**Description:**
Even after call  __detach() and __gracefulStop(), the service receives the data, and the server starts again.

**Steps to reproduce:**
Run the following code by using `ballerina run` command
```ballerina
import ballerina/http;
import ballerina/log;
import ballerina/runtime;

listener http:Listener retryServer = new (21034);

service retryService  = @http:WebSocketServiceConfig {path: "/websocket"} service {

    resource function onOpen(http:WebSocketCaller caller) {
        log:printInfo("The Connection ID: " + caller.getConnectionId());
    }

    resource function onText(http:WebSocketCaller caller, string text, boolean finalFrame) {
        log:printInfo(text);
    }
};


service retryClientCallbackService = @http:WebSocketServiceConfig {} service {
    resource function onText(http:WebSocketClient wsEp, string text) {
        log:printInfo(text);
    }
};

public function main() {
    checkpanic retryServer.__start();
    checkpanic retryServer.__attach(retryService);
    runtime:sleep(1000);
    http:WebSocketClient wsClientEp = new ("ws://localhost:21034/websocket", { callbackService:
                    retryClientCallbackService, handShakeTimeoutInSeconds: 5});
    checkpanic wsClientEp->pushText("Hi ballerina");
    runtime:sleep(500);
    checkpanic retryServer.__detach(retryService);
    checkpanic retryServer.__gracefulStop();
    runtime:sleep(1000);
    checkpanic wsClientEp->pushText("Hi balerina");
}
```

**Output**
```[ballerina/http] started HTTP/WS listener 0.0.0.0:21034
2020-09-09 11:05:21,602 INFO  [] - The Connection ID: f01898fffeab1639-000012ab-00000002-2a7a8124464c7fbf-53af5deb 
2020-09-09 11:05:21,619 INFO  [] - Hi ballerina 
[ballerina/http] stopped HTTP/WS listener 0.0.0.0:21034
2020-09-09 11:05:23,121 INFO  [] - Hi balerina 
[ballerina/http] started HTTP/WS listener 0.0.0.0:21034

```

**Comment by chamil321** [comment] 2021-06-29 04:41
Could reproduce the issue in beta1 with following code. Issue is with the `gracefulStop()`. But the `detach` seems to be working fine
```
import ballerina/http;
import ballerina/io;
import ballerina/log;
import ballerina/lang.runtime;

http:Listener listenerMethodbackendEP = check new(9090);
http:Client listenerMethodTestClient = check new("http://localhost:9090");

http:Service listenerMethodMock1 = service object {
    resource function get .(http:Caller caller, http:Request req) {
        error? responseToCaller = caller->respond("Mock1 invoked!");
        if (responseToCaller is error) {
            log:printError("Error sending response from mock service", 'error = responseToCaller);
        }
    }
};

public function main() returns error? {
    checkpanic listenerMethodbackendEP.attach(listenerMethodMock1);
    checkpanic listenerMethodbackendEP.start();
    runtime:sleep(1);
    string a = check listenerMethodTestClient->get("/");
    io:println("a");
    io:println(a);
    runtime:sleep(0.5);
    // checkpanic listenerMethodbackendEP.detach(listenerMethodMock1);
    checkpanic listenerMethodbackendEP.gracefulStop();
    runtime:sleep(1);
    string b = check listenerMethodTestClient->get("/");
    io:println("b");
    io:println(b);
}
```
Output
```
[ballerina/http] started HTTP/WS listener 0.0.0.0:9090
a
Mock1 invoked!
[ballerina/http] stopped HTTP/WS listener 0.0.0.0:9090
b
Mock1 invoked!
```

**Comment by chamil321** [comment] 2021-07-13 09:19
Implementation wise, the gracefulStop unbinds the listener port by calling `close()` ( `future.channel().close().sync();`) on the `ChannelFuture` returned from the `serverBootstrap.bind()` call. The `close()` will stop accepting new connections.

To destroy the server connector, the 
```
ChannelGroup.close()
EventLoopGroup.group.shutdownGracefully()
```
should be called. But ATM it cannot be done as separate EventLoopGroups are not created for each server connectors.

Hence, already created connection will exist until client close it and no more new connections are created. A sample to observe the behaviour

```
import ballerina/http;
import ballerina/io;

http:Listener listenerMethodbackendEP = check new(9090);
http:Client listenerMethodTestClient = check new("http://localhost:9090");

http:Service listenerMethodMock1 = service object {
    resource function get .(http:Caller caller, http:Request req) returns error? {
        return caller->respond("Mock1 invoked!");
    }
};

public function main() returns error? {
    checkpanic listenerMethodbackendEP.attach(listenerMethodMock1);
    checkpanic listenerMethodbackendEP.start();
    string a = check listenerMethodTestClient->get("/");
    io:println(a);
    checkpanic listenerMethodbackendEP.gracefulStop();

    // Create new client with keepAlive never config. First call uses already existing connection, so it will not fail
    // Subsequent call will try creating new connection with listener and it will fail
    http:Client listenerMethodTestClient = check new("http://localhost:9090", 
                                http1Settings = { keepAlive: http:KEEPALIVE_NEVER });
    string b = check listenerMethodTestClient->get("/");
    io:println(b);
    string c = check listenerMethodTestClient->get("/");
}
```
Output
```
[ballerina/http] started HTTP/WS listener 0.0.0.0:9090
Mock1 invoked!
[ballerina/http] stopped HTTP/WS listener 0.0.0.0:9090
Mock1 invoked!
error: Something wrong with the connection
```

Hence closing this issue as docs are updated in ballerina-platform/module-ballerina-http#526

**Closed by chamil321** 2021-07-13 09:19 UTC
Labels: Points/3, Priority/High, Team/PCP, Type/Bug, module/http
