### ISSUE TITLE
Build with bal test native workflow failing for graphql module

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-standard-library#3634] opened 2022-11-10 07:26 UTC
**Description:**
$Subject

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
Workflow is falling in both windows and linux due to following issues
https://github.com/ballerina-platform/ballerina-lang/issues/38613
https://github.com/ballerina-platform/ballerina-lang/issues/38614

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment] 2022-11-22 10:50
Removing the bug label, since this is not a bug in the GraphQL package.

**Comment by ThisaruGuruge** [comment] 2022-12-21 15:08
Closing as this is now fixed.

**Closed by ThisaruGuruge** 2022-12-21 15:08 UTC
Labels: Type/Task, module/graphql, Team/PCM
