### ISSUE TITLE
GraphiQL doesn't show the details of Interfaces implmenting Interfaces

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#3907] opened 2023-01-09 07:20 UTC
**Description:**
Consider the following GraphQL service:
```ballerina
import ballerina/graphql;

type Profile distinct service object {
    resource function get name() returns string;
};

type Teacher distinct service object {
    *Profile;
    resource function get school() returns string;
};

distinct service class HighSchoolTeacher {
    *Teacher;

    private final string name;
    private final string school;
    private final string subject;

    function init(string name, string school, string subject) {
        self.name = name;
        self.school = school;
        self.subject = subject;
    }

    resource function get name() returns string {
        return self.name;
    }

    resource function get school() returns string {
        return self.school;
    }

    resource function get subject() returns string {
        return self.subject;
    }
}

service /graphql on new graphql:Listener(9090) {
    resource function get profile() returns Profile {
        return new HighSchoolTeacher("Walter White", "J. P. Wynne", "Chemistry");
    }
}
```
The schema for this service should be as follows:
```graphql
type Query {
  profile: Profile!
}

interface Teacher implements Profile {
  school: String!
  name: String!
}

type HighSchoolTeacher implements Profile & Teacher {
  name: String!
  school: String!
  subject: String!
}

interface Profile {
  name: String!
}
``` 
But it doesn't display the interface implementing interface details(`interface Teacher implements Profile`) in GraphiQL. May be an issue with the GraphiQL client. Check the below screenshot:
![Screenshot from 2023-01-09 12-46-40](https://user-images.githubusercontent.com/35717653/211257361-65ba46f2-8392-4e0c-8a94-5703cd870b96.png)

**Comment by ThisaruGuruge** [comment] 2023-01-09 07:43
Don't we have a test for this @MohamedSabthar? If tests are available, this must be an issue in the GraphiQL client. Shall we check that?

**Comment by MohamedSabthar** [comment] 2023-01-09 08:40
@ThisaruGuruge yes we do. 
I also tested the above code with apollo sandbox seems it's giving the expected schema. seems this is an issue with GraphiQL. 
<img width="654" alt="image" src="https://user-images.githubusercontent.com/43032716/211268293-9c68f8a3-d572-48c5-875f-4b1a6db9d4ac.png">

**Comment by ThisaruGuruge** [comment] 2023-01-09 10:15
> @ThisaruGuruge yes we do. I also tested the above code with apollo sandbox seems it's giving the expected schema. seems this is an issue with GraphiQL. <img alt="image" width="654" src="https://user-images.githubusercontent.com/43032716/211268293-9c68f8a3-d572-48c5-875f-4b1a6db9d4ac.png">

Let's create an issue in the GraphiQL repo.

**Comment by MohamedSabthar** [comment] 2023-01-10 08:09
> Let's create an issue in the GraphiQL repo.
Created https://github.com/graphql/graphiql/issues/2990

**Comment by ThisaruGuruge** [comment] 2023-01-31 05:10
Closing this since this is not a bug in the Ballerina GraphQL package.

**Closed by ThisaruGuruge** 2023-01-31 05:10 UTC
Labels: Type/Bug, module/graphql, Team/PCM
