### ISSUE TITLE
Access Logs or Trace Logs are not printing when interceptors used

### ISSUE THREAD

**Issue by menakaj** [ballerina-platform/ballerina-standard-library#3546] opened 2022-10-21 10:37 UTC
**Description:**

When interceptors are used in a ballerina service, access logs and trace logs are not printing to the console. 

**Steps to reproduce:**
Code sample:

```ballerina
import ballerina/http;

service class RequestPreProcessor {
    *http:RequestInterceptor;
    resource function 'default [string... path](
        http:RequestContext ctx,
        http:Request req
    ) returns http:NextService|http:Unauthorized|error? {
        return ctx.next();
    }
}

listener http:Listener endpoint = check new(9092, {});

RequestPreProcessor requestPreProcessor = new;

@http:ServiceConfig {
    interceptors: [requestPreProcessor]
}
service / on endpoint {
    
    resource function get one(string name) returns string{
        return name;
        
    }

    resource function post two(string name) returns string{
        return name;
        
    }
    resource function get three(string name) returns string{
        return name;
        
    }
}

```

1. Run the above service with trace logs and http access logs enabled. (https://ballerina.io/learn/by-example/http-access-logs/)

following logs are printed but, access logs or trace logs are not printing.

```
bal run test.bal -- -Cballerina.http.traceLogConsole=true
Compiling source
        test.bal

Running executable

ballerina: HTTP trace log enabled
ballerina: HTTP access log enabled
```

**Affected Versions:**

2201.1.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharmiganK** [comment] 2022-10-25 03:37
@menakaj I have tested the given code in `2201.1.1` and in the latest version : `2201.2.2`. For both versions I am getting the trace logs and access logs. (tested on Mac OS)

Can you also check again? Also what os are you using?

A simple request for the following endpoint : `http://localhost:9092/one?name=Tharmi` produced the following logs in the console : (tested with cURL client and ballerina http client)

```console
ballerina: HTTP trace log enabled
ballerina: HTTP access log enabled
[2022-10-25 08:53:14,743] TRACE {http.tracelog.downstream} - [id: 0x4cb8ce14] REGISTERED  
[2022-10-25 08:53:14,767] TRACE {http.tracelog.downstream} - [id: 0x4cb8ce14, correlatedSource: n/a, host:/127.0.0.1:9092 - remote:/127.0.0.1:55213] ACTIVE  
[2022-10-25 08:53:14,784] TRACE {http.tracelog.downstream} - [id: 0x4cb8ce14, correlatedSource: n/a, host:/127.0.0.1:9092 - remote:/127.0.0.1:55213] INBOUND: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
GET /one?name=Tharmi HTTP/1.1
Host: localhost:9092
User-Agent: curl/7.79.1
Accept: */*  
[2022-10-25 08:53:14,816] TRACE {http.tracelog.downstream} - [id: 0x4cb8ce14, correlatedSource: n/a, host:/127.0.0.1:9092 - remote:/127.0.0.1:55213] INBOUND: EmptyLastHttpContent, 0B  
[2022-10-25 08:53:14,818] TRACE {http.tracelog.downstream} - [id: 0x4cb8ce14, correlatedSource: n/a, host:/127.0.0.1:9092 - remote:/127.0.0.1:55213] READ COMPLETE  
[2022-10-25 08:53:14,869] TRACE {http.tracelog.downstream} - [id: 0x4cb8ce14, correlatedSource: n/a, host:/127.0.0.1:9092 - remote:/127.0.0.1:55213] OUTBOUND: DefaultFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 6, cap: 6, components=1))
HTTP/1.1 200 OK
content-type: text/plain
content-length: 6
server: ballerina
date: Tue, 25 Oct 2022 08:53:14 +0530, 6B
Tharmi  
127.0.0.1 - - [25/Oct/2022:08:53:14 +0530] "GET /one?name=Tharmi HTTP/1.1" 200 6 "-" "curl/7.79.1" 
[2022-10-25 08:53:14,873] TRACE {http.tracelog.downstream} - [id: 0x4cb8ce14, correlatedSource: n/a, host:/127.0.0.1:9092 - remote:/127.0.0.1:55213] FLUSH  
[2022-10-25 08:53:14,900] TRACE {http.tracelog.downstream} - [id: 0x4cb8ce14, correlatedSource: n/a, host:/127.0.0.1:9092 - remote:/127.0.0.1:55213] READ COMPLETE  
[2022-10-25 08:53:14,910] TRACE {http.tracelog.downstream} - [id: 0x4cb8ce14, correlatedSource: n/a, host:/127.0.0.1:9092 - remote:/127.0.0.1:55213] INACTIVE  
[2022-10-25 08:53:14,914] TRACE {http.tracelog.downstream} - [id: 0x4cb8ce14, correlatedSource: n/a, host:/127.0.0.1:9092 - remote:/127.0.0.1:55213] UNREGISTERED  
```

**Comment by TharmiganK** [comment] 2022-12-02 03:53
@menakaj if this is not reproducible can you close this issue?

**Comment by TharmiganK** [comment] 2022-12-05 03:20
Closing this issue due since this issue is not reproducible. Reopen the issue if this is reproducible.

**Closed by TharmiganK** 2022-12-05 03:20 UTC
Labels: Type/Bug, module/http, Team/PCM, Reason/Invalid
