### ISSUE TITLE
Add a way to specify a task to start immediately 

### ISSUE THREAD

**Issue by Drifftr** [ballerina-platform/ballerina-standard-library#2768] opened 2022-03-10 04:50 UTC
**Description:**
Currently if we need to start a task we need to provide the time(Civil Time) as a mandatory parameter 
ex :- 
```
task:scheduleOneTimeJob(new Job(...), time)
```
But there is a valid use case where we need to start the task immediately(now). Currently even if we need to start now we have to pass time now and this might fail due to the execution time difference between the lines.
ex :- 
```
time:Civil time = time:utcToCivil(time:utcNow()); // executes at 11:22:34.1312
...
task:scheduleOneTimeJob(new Job(...), time) // executes at 11:22:34.1313 and fails since we provide a past time
```
This fails since we provides a past time to the task. So its better if we can have a method to start the task now.
As an example Quartz Trigger has startNow() and startsAt(long time) both. So we can use startNow() if we need to start immediately.

**Describe your problem(s)**
Can cause issues due to execution time delay when we need to start a task immediately.

**Describe your solution(s)**
Introduce a flag or a new function which implements startNow() like functionality in Quartz Trigger.

**Comment by LahiruRajapaksha** [comment] 2022-03-15 06:41
The issue is now fixed. Tested it on Staging. Can you also please verify @SkNuwanTissera

**Comment by daneshk** [comment] 2022-04-20 16:41
I am closing this issue since we provided a solution for the query.

**Closed by daneshk** 2022-04-20 16:41 UTC
Labels: Type/Improvement, module/task
