### ISSUE TITLE
Special characters in resource path caused issues in action invocation

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-standard-library#4196] opened 2023-03-14 00:03 UTC
**Description:**
$subject refer to the sample code below.

**Steps to reproduce:**

```ballerina
import ballerina/http;
import ballerina/io;

public function main() returns error? {
    http:Client openWeather = check new("https://api.openweathermap.org");
    json|error res = openWeather->get("/data/2.5/forecast?lat=30.266666&lon=-97.733330&appid=<appid>");
    io:println(res); //This works

    io:println("1---------------");

    json|error res2 = openWeather->/data/["2.5"]/forecast.get(lat=30.266666, lon=-97.733330, appid="<appid>");
    io:println(res2);//This works

    io:println("2---------------");//Following does not work
    json|error res3 = openWeather->/data/\2\.5/forecast.get(lat=30.266666, lon=-97.733330, appid="<appid>");
    io:println(res3);
}

```

Note : I used a free version of https://openweathermap.org/api to generate tokens.

Request hangs and it gives the following error.

```sh
error PayloadBindingClientError ("http:ApplicationResponseError creation failed: 404 response payload extraction failed",error GenericClientError ("Error occurred while retrieving the json payload from the response",error ParserError ("Error occurred while extracting content from message : Idle timeout triggered while reading inbound response headers")))
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharmiganK** [comment] 2023-03-20 05:12
Seems like the url is resolved like this: `https://api.openweathermap.org/data/.5/` since we are escaping the character `2`. **So I don't think this is a bug.**

This is reproducible even with the simple client example without http:
```bal
import ballerina/log;
client class Client {

    resource function get test/path/[string val]/end() returns string {
        return val;
    }
}

public function main() returns error? {
    Client clientEP = new;
    string val = clientEP->/test/path/\2\.5/end;
    log:printInfo("response 2 received", 'value = val);
}
```

Running the above sample will print value as `.5`.

And **the request hanging issue might be a regression issue with the above resolved url and the weather server** (since it is not reproducible with the simple bal server - this will return a`500 - Illegal character in url` error).

The first two calls will work with Ballerina clients. And I believe, in the third call you want to pass the value directly in the url, that is not supported since we cannot have identifiers starting with numerical values. 

But we could improve the second call like this if we support basic types as path segments (currently we only allow `string` types):
```bal
json|error res2 = openWeather->/data/[2.5]/forecast.get(lat=30.266666, lon=-97.733330, appid="<appid>");
```

**Comment by shafreenAnfar** [comment] 2023-03-27 11:56
Closing this as answered.

**Closed by shafreenAnfar** 2023-03-27 11:56 UTC
Labels: Priority/High, Type/Bug, module/http, Team/PCM, Reason/Invalid
