### ISSUE TITLE
GraphQL omits some of the record fields

### ISSUE THREAD

**Issue by yashodgayashan** [ballerina-platform/ballerina-standard-library#2458] opened 2021-12-05 17:31 UTC
**Description:**
When get GraphQL call and sometime it omits some of the fields as follows.

```json
{
    "data": {
        "components": [
            {
                "projectId": "<project-id>",
                "id": "3c60570d-6360-4732-adf0-95dcdde3787d",
                "name": "greetings",
                "handler": "0grw2w",
                "displayName": "Greetings",
                "displayType": "restAPI",
                "version": "1.0.0",
                "createdAt": "2021-11-09T10:01:58.17184Z",
                "orgHandler": "<org-handler>"
            },
            {
                "projectId": "<project-id>",
                "id": "9fa70278-1826-410c-814f-d846e989cbb4",
                "name": "greetings9nov2021-1",
                "handler": "ul2qp4",
                "displayName": "Greetings9Nov2021-1",
                "displayType": "restAPI",
                "version": "1.0.0",
                "createdAt": "2021-11-09T10:56:38.5734802Z",
                "orgHandler": "<org-handler>"
            },
            {
                "projectId": "<project-id>",
                "id": "ef755143-047f-4c7e-8920-7f7be12ee101",
                "name": "manualtask",
                "handler": "2hsaeb",
                "displayName": "ManualTask",
                "displayType": "manualTrigger",
                "version": "1.0.0",
                "createdAt": "2021-11-09T11:21:46.6996433Z",
                "orgHandler": "<org-handler>"
            },
            {
                "projectId": "<project-id>",
                "id": "4790ccfa-d912-4fb8-bacd-eea75bc77276",
                "name": "scheduledtask",
                "handler": "xctmhb",
                "displayType": "scheduledTask",
                "version": "1.0.0",
                "createdAt": "2021-11-09T11:46:22.9402236Z",
                "orgHandler": "<org-handler>"
            },
            {
                "projectId": "<project-id>",
                "id": "019bc5e7-6688-4576-94d1-2630910b3757",
                "name": "default-webhook",
                "handler": "lyvbfi",
                "displayName": "Default Webhook",
                "displayType": "webhook",
                "version": "1.0.0",
                "createdAt": "2021-11-09T18:28:45.4276502Z",
                "orgHandler": "<org-handler>"
            },
            {
                "projectId": "<project-id>",
                "id": "8421a38d-d7f6-446c-aee9-b380c94b5039",
                "name": "greetings3",
                "handler": "6ef2ef",
                "displayName": "Greetings3",
                "displayType": "restAPI",
                "version": "1.0.0",
                "createdAt": "2021-11-09T20:20:26.2400885Z",
                "orgHandler": "<org-handler>"
            },
            {
                "projectId": "<project-id>",
                "id": "d0cd89d9-f1bc-471e-ac91-24d8a405fb7f",
                "name": "greetings4",
                "handler": "lu1jj2",
                "displayName": "Greetings4",
                "displayType": "restAPI",
                "version": "1.0.0",
                "createdAt": "2021-11-09T20:54:38.3135571Z",
                "orgHandler": "<org-handler>"
            },
            {
                "projectId": "<project-id>",
                "id": "dd174dd4-e65c-4ed0-bdf0-40030ed0e631",
                "name": "greetings6",
                "handler": "cg8sw9",
                "displayName": "Greetings6",
                "displayType": "restAPI",
                "version": "1.0.0",
                "createdAt": "2021-11-09T21:05:06.6971151Z",
                "orgHandler": "<org-handler>"
            },
            {
                "projectId": "<project-id>",
                "id": "835be4f9-dc26-4445-b908-a3da173d8196",
                "name": "manualtask2",
                "handler": "1ma5kj",
                "displayName": "ManualTask2",
                "displayType": "manualTrigger",
                "version": "1.0.0",
                "createdAt": "2021-11-09T23:32:41.7128008Z",
                "orgHandler": "<org-handler>"
            },
            {
                "projectId": "<project-id>",
                "id": "093a6e88-7f2f-4487-8aa6-e3045b35c3b1",
                "name": "scheduledtrigger2",
                "handler": "1bewes",
                "displayName": "ScheduledTrigger2",
                "displayType": "scheduledTask",
                "version": "1.0.0",
                "createdAt": "2021-11-09T23:43:03.4488795Z",
                "orgHandler": "<org-handler>"
            },
            {
                "projectId": "<project-id>",
                "id": "75ac691c-0083-4c9d-9bda-ec40f63851b8",
                "handler": "dk3dpz",
                "displayName": "Default Webhook",
                "displayType": "webhook",
                "version": "1.0.0",
                "createdAt": "2021-11-10T00:02:18.006029Z",
                "orgHandler": "<org-handler>"
            },
            {
                "projectId": "<project-id>",
                "id": "9544bad7-4b8d-4e8a-ac0a-e93cfb828852",
                "name": "greetingsbd",
                "handler": "nzlo39",
                "displayName": "Greetings",
                "displayType": "restAPI",
                "version": "1.0.0",
                "createdAt": "2021-11-26T06:00:48.006558Z",
                "orgHandler": "<org-handler>"
            },
            {
                "projectId": "<project-id>",
                "id": "d6d0c4c0-d058-4f0f-b1ae-5676558213c7",
                "name": "greetings23",
                "handler": "whbv3c",
                "displayName": "Greetings23",
                "displayType": "restAPI",
                "version": "1.0.0",
                "createdAt": "2021-11-26T06:44:31.0001082Z",
                "orgHandler": "<org-handler>"
            }
        ]
    }
}
```

In the above case in one object `name` is missing and in the other `displayName` is missing.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
GraphQL

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment] 2021-12-06 04:36
Please provide more information on this to find the root cause.

We have to look at the GraphQL service and the types in the schema first.

**Comment by yashodgayashan** [comment] 2021-12-06 11:59
We are using `slbeta3` version. 

### Resolver

```bal
isolated resource function get projects(int orgId) returns apis:Project[]|error {
        return apis:getProjectsByOrgId(orgId);
}
```

### Function

```bal
public isolated function getProjectsByOrgId(int orgId) returns Project[]|error {
    ProjectsResMapper|error resp = projectManagerClient->get("<url>");
    if resp is error {
        return utils:throwError("error occured while fetching projects", resp);
    } else {
        return from ProjectData project in resp.data
            select new (project);
    }
}

```

**Comment by ThisaruGuruge** [comment] 2021-12-06 12:03
We need to look at the `Project` data type as well.  What is `ProjectResMapper` look like? can you please provide the above information?

**Comment by yashodgayashan** [comment] 2021-12-06 12:19
Project

```bal
public isolated service class Project {

    private final ProjectData & readonly data;

    public isolated function init(ProjectData data) {
        self.data = data.cloneReadOnly();
    }

    public isolated function getId() returns string => self.data.id;

    isolated resource function get name() returns string => self.data.name;

    isolated resource function get handler() returns string? => self.data.handler;

    isolated resource function get extendedHandler() returns string? => self.data.extendedhandler;

    isolated resource function get 'version() returns string => self.data.metadata.'version;

    isolated resource function get labels() returns string? => self.data.metadata?.labels;

    isolated resource function get orgId() returns int => self.data.organizationId;

    isolated resource function get id() returns string => self.data.id;

    isolated resource function get description() returns string => self.data.description;

    isolated resource function get createdDate() returns string => self.data.createdDate;
}
```


ProjectData

```bal
public type ProjectData record {
    string id;
    string name;
    string description;
    int organizationId;
    string createdDate;
    Metadata metadata;
    string _id?;
    string? handler;
    string? extendedhandler;
};
```

Metadata

```bal
public type Metadata record {|
    string 'version;
    string labels?;
|};
```

**Comment by ThisaruGuruge** [comment] 2021-12-06 12:22
From where the `displayName` field comes from? 
Can you show the related GraphQL document as well?

**Comment by malithjayasinghe** [comment] 2021-12-07 04:25
Any updates on this one? we are currently blocked by this.

**Comment by ThisaruGuruge** [comment] 2021-12-07 06:37
> Any updates on this one? we are currently blocked by this.

We will have a call and get this sorted out.

**Comment by ThisaruGuruge** [comment] 2021-12-07 07:56
Had an offline chat with @yashodgayashan and @DimuthuMadushan. Seems like this is an issue when a resource is dispatched to the runtime. We will further analyze the issue and update it here.

If this can be fixed in the GraphQL package, we can patch it and push it to the central. Otherwise, we may have to wait for the lang build.

**Comment by ThisaruGuruge** [comment] 2021-12-07 09:05
We had a look, and this seems to be an issue in the Ballerina runtime. It has already been fixed in the ballerina-lang repo master branch. 

Therefore, this will be fixed with the SwanLake beta.6 release. 

Related lang issue: https://github.com/ballerina-platform/ballerina-lang/issues/33827

Related PRs:
- https://github.com/ballerina-platform/ballerina-lang/pull/33874
- https://github.com/ballerina-platform/ballerina-lang/pull/34067

@shafreenAnfar @warunalakshitha @daneshk

**Comment by ThisaruGuruge** [comment] 2021-12-08 06:28
Closing this since this will be fixed with the next release. Please re-open if the problem still occurs in the beta.6 release.

**Closed** 2022-02-15 05:10 UTC
Labels: Priority/High, Priority/Blocker, Type/Bug, module/graphql, Team/PCP
