### ISSUE TITLE
Avoid Adding All Possible Federated Directives to SDL String in GraphQL Subgraph

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-standard-library#4681] opened 2023-07-26 10:32 UTC
**Description:**
The Current Implementation of Subgraph Includes All the Federated Directives Listed Here: https://www.apollographql.com/docs/federation/subgraph-spec.

Since the current implementation only supports the @key directive, we should only add this directive to the auto-generated SDL string.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment] 2023-07-27 09:08
Closing as this has to be confirmed from the Apollo federation spec. @DimuthuMadushan let's link the issue here.

**Comment by DimuthuMadushan** [comment] 2023-07-27 09:28
issue: https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/475

**Comment by DimuthuMadushan** [comment] 2023-07-28 03:42
Re-open the issue since this has confirmed by the Apollo federation. https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/475#issuecomment-1654246013

**Closed** 2023-07-28 07:31 UTC
Labels: Type/Bug, module/graphql, Team/PCM, Reason/Other
