### ISSUE TITLE
[Dispatching]Cannot add 2 different API resources with same end URL Template - 404 Error

### ISSUE THREAD

**Issue by Sumudu-Sahan** [ballerina-platform/ballerina-standard-library#1095] opened 2021-03-01 17:49 UTC
**Description:**
Cannot use 2 different API resources with same last URL template values. When invoking the 2nd API resource, will receive 404 response code.

**Steps to reproduce:**
You can reproduce the issue by using the below code segment. 

- Resource 1: /path/{id}
- Resource 2: /path/{noteasdf}/aa/{id}

```
import ballerina/http;
http:ListenerConfiguration helloWorldEPConfig = {
    secureSocket: {
        keyStore: {
            path: "/Users/viraj/Documents/APIM-2/resolve_merge/viraj_4/product-microgateway/distribution/target/wso2am-micro-gw-macos-3.2.2-SNAPSHOT/runtime/bre/security/ballerinaKeystore.p12",
            password: "ballerina"
        }
    }
};
service hello on new http:Listener(8181, helloWorldEPConfig) {
    @http:ResourceConfig {
        methods: ["GET"],
        path: "/path/{id}"
    }
    resource function sayHello2(http:Caller caller,
        http:Request req) returns error? {
        check caller->respond("Hello, World - 2!");
    }
    @http:ResourceConfig {
        methods: ["GET"],
        path: "/path/{noteasdf}/aa/{id}"
    }
    resource function sayHello3(http:Caller caller,
        http:Request req) returns error? {
        check caller->respond("Hello, World! 3");
    }
}
```

**Comment by chamil321** [comment] 2021-06-04 13:16
Suggested solution might help to understand the behaviour when fixing the issue. Hence.
```
These are the three main resources of the API which are subjected to the fore-mentioned issue. 

notebook/{id} 
notebook/{notebookId}/entry/{id}
/notebook/{notebookId}/entry/{notebookEntryId}/content/{id}

Here, the id parameter has three separate meanings across the three resources. What we have to suggest is to make it consistent such that the same parameter does not have various meanings. And that is the best practice to follow when writing an API (even though it is not governed by the openapi spec). This approach can be used until this issue is fixed. In that case, the resources would look like this. 

notebook/{notebookId} 
notebook/{notebookId}/entry/{notebookEntryId}
/notebook/{notebookId}/entry/{notebookEntryId}/content/{id}
```

**Comment by chamil321** [comment] 2021-06-04 13:19
Duplicate of https://github.com/ballerina-platform/ballerina-standard-library/issues/342

**Closed** 2021-06-16 08:44 UTC
Labels: Priority/High, Type/Bug, module/http
