### ISSUE TITLE
The API Docs of time module doesn't contain enough information on format strings

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-standard-library#922] opened 2021-01-31 09:26 UTC
As per the table in  API docs `V` is for time-zone ID.  (https://ballerina.io/swan-lake/learn/api-docs/ballerina/#/ballerina/time/1.0.7)

So if we run the code below : 

```ballerina
import ballerina/time;
import ballerina/io;
public function main() {
    time:Time currentTime = time:currentTime();

    string|time:TimeError format = time:format(currentTime, "V");
    if (format is string) {
        io:println(format);
    } else {
        io:println(format.message());
    }
}
```

It gives the below error.

```Invalid Pattern: V```

The reason is it should be `VV`.   If the count of letters is two, then the time-zone ID is output. Any other count of letters throws IllegalArgumentException.

`The count of pattern letters determines the format. `

Refer to the last paragraph of `Patterns for Formatting and Parsing` in https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/format/DateTimeFormatter.html

Add the necessary rules to the ballerina time module API docs to  make this and all the count related formats clear.

**Comment by daneshk** [comment] 2021-02-22 12:10
The issue is fixed in the master branch, hence closing

**Closed by daneshk** 2021-02-22 12:10 UTC
Labels: Type/Docs, Type/Improvement, module/time
