### ISSUE TITLE
Stored Procedure call returns "The statement must be executed before any results can be obtained."

### ISSUE THREAD

**Issue by Shairam** [ballerina-platform/ballerina-standard-library#1409] opened 2021-06-01 05:11 UTC
**Description:**
Trying to call a stored procedure from a Ballerina service and got the following error:
```
time = 2021-06-01T09:59:20.750+05:30 level = ERROR module = sample/jdbc message = "Error while executing SQL query: {CALL Register( ? ,  ? ,  ? ,  ? ,  ? ,  ? )}. The statement must be executed before any results can be obtained.." 
error: Register stored proc failed: Error while executing SQL query: {CALL Register( ? ,  ? ,  ? ,  ? ,  ? ,  ? )}. The statement must be executed before any results can be obtained.. {}
```
This `Register` stored procedure calls two other stored procedures internally. 

**Steps to reproduce:**
1) The script to create these DB objects can be shared on request. 
2) Create a simple ballerina program to call these stored procedures.

**OS, DB, other environment details and versions:**
Ballerina version: SL Alpha-02 (Tested with Alpha-05 as well but no luck)
Driver: mssql-jdbc-9.2.1.jre11.jar
DB server: Azure SQL Server

**Comment by Shairam** [comment] 2021-06-01 06:37
Tried the same call with JAVA as below and was successful:
```
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.CallableStatement;
 
public class Main {
 
    public static void main(String[] args) {
        Connection conn = null;
 
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String dbURL = "jdbc:sqlserver://localhost:1433;DatabaseName=master";
            String user = "sa";
            String pass = "root";
            conn = DriverManager.getConnection(dbURL, user, pass);
            if (conn != null) {
                try(CallableStatement cstmt = conn.prepareCall("{call Register(?, ?, ?, ?, ?, ?)}"); ) {  
                    cstmt.setString(1,"Sec-Amy123");
                    cstmt.setString(2,"asthash");
                    cstmt.setString(3, "99");
                    cstmt.registerOutParameter("obsid", java.sql.Types.VARCHAR);  
                    cstmt.registerOutParameter("vn", java.sql.Types.VARCHAR);
                    cstmt.registerOutParameter("astchanged", java.sql.Types.BOOLEAN);
                    cstmt.execute();  
                    System.out.println("Obs ID: " + cstmt.getString("obsid"));  
                    System.out.println("vn: " + cstmt.getString("vn")); 
                    System.out.println("ast changed: " + cstmt.getBoolean("astchanged")); 
                }  
            }
 
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex){
            ex.printStackTrace();
        } finally {
            try {
                if (conn != null && !conn.isClosed()) {
                    conn.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
}
```

**Comment by daneshk** [comment] 2021-06-02 03:36
We found the root cause for this issue. we are working on the resolution. will keep you updates

**Comment by Shairam** [comment] 2021-06-02 03:43
Ack. Thanks for the update.

**Comment by Shairam** [comment] 2021-06-02 06:33
@daneshk can we expect this to be fixed in Ballerina Beta version?

**Comment by Shairam** [comment] 2021-06-03 04:15
Hi all, 
Appreciate if this fix can be patched to Beta1, since we are currently blocked with this for the task https://github.com/wso2-enterprise/choreo/issues/4767

**Comment by daneshk** [comment] 2021-06-04 02:11
once the fix is merged, we will push the SQL connectors to the central with a new version. you can pull the latest from the central. we don't need to pack. @niveathika WDYT?

**Comment by daneshk** [comment] 2021-06-04 10:59
This issue is fixed in SL beta1 release. SQL: 0.6.0-beta.1.1 and JDBC: 0.6.0-beta.1.1 versions

**Closed by daneshk** 2021-06-04 11:00 UTC
Labels: Priority/Blocker, Priority/High, Team/DIU, Type/Bug, module/java.jdbc
