### ISSUE TITLE
Add advance filter related changes to the generated clients

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3468] opened 2022-10-06 08:52 UTC
**Description:**
With the advanced filter support using query syntax, there are few changes related to the `read()` function and add new `execute()` function.

**Comment by niveathika** [comment] 2022-10-06 11:11
Duplicate of https://github.com/ballerina-platform/ballerina-standard-library/issues/3454

**Closed by niveathika** 2022-10-06 11:11 UTC
Labels: Type/Task, Team/DIU, module/persist
