### ISSUE TITLE
java.lang.UnsatisfiedLinkError when running http2 service with secure socket in Docker

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-standard-library#1446] opened 2021-06-10 08:16 UTC
**Description:**

Following error is thrown when running an http2 service with the secure socket config in Docker.  The issue is not there if the secure socket configs of the listener are removed. 

```
error: java.lang.UnsatisfiedLinkError {"message":"failed to load the required native library","cause":error("java.lang.IllegalArgumentException",message="Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]")}
	at ballerina.http.1_1_0-beta_1:externInitEndpoint(http_service_endpoint.bal:92)
	   ballerina.http.1_1_0-beta_1.Listener:init(http_service_endpoint.bal:35)
	   ballerina.http.1_1_0-beta_1.Listener:$init$(http_service_endpoint.bal:22)
```

The source code is as below.

```ballerina
import ballerina/http;
import ballerina/log;

listener http:Listener securedEP = new(9090, {
    httpVersion: "2.0",
    secureSocket: {
        key: {
            path: "./security/ballerinaKeystore.p12",
            password: "ballerina"
        }
    }
});

final http:Client nettyEP = check new("https://netty:8688", {
    secureSocket:  {
        cert: {
            path: "./security/ballerinaTruststore.p12",
            password: "ballerina"
        },
        verifyHostName: false
    }
});

service /passthrough on securedEP {
    resource function post .(http:Caller caller, http:Request clientRequest) {
        http:Response|http:ClientError response = nettyEP->forward("/service/EchoService", clientRequest);
        if (response is http:Response) {
            error? result = caller->respond(response);
        } else {
            log:printError("Error at h2_h1_passthrough", 'error = response);
            http:Response res = new;
            res.statusCode = 500;
            res.setPayload(response.message());
            error? result = caller->respond(res);
        }
    }
}

```

**Steps to reproduce:**
1. Create a Docker image with the above source.
2. Run the docker container

**Affected Versions:**
sl-beta1

**OS, DB, other environment details and versions:**

```
$ java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-alpine-r0)
OpenJDK 64-Bit Server VM (build 11.0.5+10-alpine-r0, mixed mode)

$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.6
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by BuddhiWathsala** [comment] 2021-12-17 05:06
Seems this is similar to this gRPC issue https://github.com/ballerina-platform/ballerina-standard-library/issues/2492

**Comment by shafreenAnfar** [comment] 2021-12-22 06:34
I tried with beta6 and couldn't reproduce.  I started the service and sent a request.

```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.3
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
```
Docker file
```docker
FROM adoptopenjdk/openjdk11:jre-11.0.9.1_1-alpine
WORKDIR /usr/src/app
EXPOSE 9090
COPY ./tmp.jar ./
COPY ./ballerinaKeystore.p12 ./
COPY ./ballerinaTruststore.p12 ./
CMD java -XX:+UseContainerSupport \
    -XX:MinRAMPercentage=33.3 \
    -XX:MaxRAMPercentage=33.3 \
    -jar tmp.jar
```

**Comment by shafreenAnfar** [comment] 2021-12-22 06:54
When `bal run` is used to compile and execute, there was a similar issue and it was fixed with https://github.com/ballerina-platform/ballerina-lang/issues/34357

**Comment by shafreenAnfar** [comment] 2021-12-22 06:55
I am closing the issue as it is no longer valid.

**Closed** 2021-12-22 06:55 UTC
Labels: Priority/High, Priority/Blocker, Type/Bug, module/http, Team/PCP
