### ISSUE TITLE
JDBC BBE build failure

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#2424] opened 2021-11-23 04:20 UTC
**Description:**
Running the [JDBC query operation BBE](https://ballerina.io/learn/by-example/jdbc-query-operation.html?is_ref_by_example=true) returns the compilation error before

`
ERROR [ballerinax/java.jdbc/1.0.0::client.bal:(65:5,69:16)] mismatched function signatures: expected 'public function queryRow(ballerina/sql:1.1.0:ParameterizedQuery sqlQuery, typedesc<anydata> returnType) returns (returnType|ballerina/sql:1.1.0:Error)', found 'public function queryRow(ballerina/sql:1.1.0:ParameterizedQuery sqlQuery, typedesc returnType) returns (returnType|ballerina/sql:1.1.0:Error)'
`

**Affected Versions:**
SLBeta4

**Comment by niveathika** [comment] 2021-11-23 04:32
Ballerina playground seems to have only jdbc 1.0.0 in the cache. However, this should pull the latest from central if Dependencies.toml is not found.

**Comment by niveathika** [comment] 2021-11-23 06:12
Duplicate of https://github.com/ballerina-platform/ballerina-standard-library/issues/2428

**Comment by MadhukaHarith92** [comment] 2021-11-23 10:21
Closing since this is a duplicate.

**Closed by MadhukaHarith92** 2021-11-23 10:21 UTC
Labels: Points/1, Type/Bug, module/java.jdbc, Team/DIU
