### ISSUE TITLE
Conflicting jars when building nBallerina

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-standard-library#3011] opened 2022-06-17 06:58 UTC
**Description:**
I was building nBallerina with `2201.1.1-SNAPSHOT` (built locally). Following warning was printed:
```
Generating executable
        warning: Detected conflicting jar files:
                'io-native-1.2.1.jar' dependency of 'ballerina/os' conflict with 'io-native-1.2.2.jar' dependency of 'ballerina/io'
        target/bin/nballerina.jar
```

**Steps to reproduce:**
See description

**Affected Versions:**
2201.1.1-SNAPSHOT

**Comment by niveathika** [comment] 2022-06-19 14:31
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/32666

**Closed by niveathika** 2022-06-19 14:31 UTC
Labels: Type/Bug, module/io, module/os
