### ISSUE TITLE
Remove usage of `ballerina-core` module from ballerina-lang

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-standard-library#2824] opened 2022-03-30 06:48 UTC
**Description:**
$subject
As the above `ballerina-core` module contains the old ballerina implementations and it is not further maintained, it is preferred to remove the usage of this module and use the `ballerina-runtime` module instead. 

https://github.com/ballerina-platform/module-ballerina-ftp/blob/23f25ca20c6a7067e87ee5c258b8145977ca1418/native/src/main/java/io/ballerina/stdlib/ftp/util/BufferHolder.java

https://github.com/ballerina-platform/module-ballerina-mime/blob/71c52f1262ecda12abc3632e0f8b4f29d17015fb/native/src/main/java/io/ballerina/stdlib/mime/util/ExternTestUtils.java

**Comment by niveathika** [comment] 2022-03-30 06:53
Duplicate of https://github.com/ballerina-platform/ballerina-standard-library/issues/2802

**Closed by niveathika** 2022-03-30 06:53 UTC
Labels: module/mime, module/ftp
