### ISSUE TITLE
Constraint validation fails, if the record consists of annotation other than `@constraint`

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3806] opened 2022-12-08 18:09 UTC
**Description:**
```ballerina
type Order record {|
    string id;
    sql:Column{name="order_date"}
    time:Date orderDate;
    string productId;
    int quantity;
|};

service / on new http:Listener(8080) {

    function init() returns error? {
    }

    resource function post 'order(@http:Payload Order salesOrder) returns http:Created|error {
      // Valid payload fails
    }
}

```

```log
payload validation failed: Unexpected error found due to typedesc and value mismatch
```

**Comment by niveathika** [comment] 2022-12-08 18:15
Moving this to constraint package as the payload validation fails,
```
import ballerina/time;
import ballerina/constraint;
import ballerina/sql;

type Order record {|
    string id;
    @sql:Column {name: "order_date"}
    time:Date orderDate;
    @sql:Column {name: "product_id"}
    string productId;
    int quantity;
|};

public function main() returns error? {
    Order req = {
        id: "10",
        productId: "23",
        quantity: 5,
        orderDate: {year: 2022, month: 12, day: 8}
    }; 
    req = check constraint:validate(req);
}
```

**Comment by TharmiganK** [comment] 2023-01-05 03:59
This is duplicate of this issue https://github.com/ballerina-platform/ballerina-standard-library/issues/3817. And closing it here as the related issue has been fixed.

**Closed by TharmiganK** 2023-01-05 03:59 UTC
Labels: Priority/High, Type/Bug, Reason/EngineeringMistake, module/constraint
