### ISSUE TITLE
Constrains should let user override the default error message

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#3940] opened 2023-01-17 07:30 UTC
At the moment there is no user friendly way to override the default error message. It would be good if we can have something like the below (which is also supported by other frameworks).

```ballerina
// Constraint on the `int` type.
@constraint:Int {
    minValue: 18
    message: "Student age should be greater than 18"
}
type Age int;
```

**Comment by TharmiganK** [comment] 2023-01-17 07:32
Duplicate of : https://github.com/ballerina-platform/ballerina-standard-library/issues/3211

**Closed** 2023-01-17 07:33 UTC
Labels: Type/Improvement, Team/PCM, module/constraint
