### ISSUE TITLE
HTTP CB test cases failing intermittently after defaulting HTTP version as 2.0

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#3050] opened 2022-07-01 09:00 UTC
**Description:**
> $subject

Followng test cases are failing:
- testCircuitBreakerWithoutStatusCodes2

**Comment by TharmiganK** [comment] 2022-07-14 04:34
This was experienced when running the tests in locally after defaulting the HTTP server version to H2.

Tried to reproduce it locally,
1. by running `testCircuitBreakerWithoutStatusCodes` test in a loop for multiple times (about 100)
2. by running some sub set of CB tests with `testCircuitBreakerWithoutStatusCodes` test in a loop for multiple times (about 50)
3. by running all the tests for multiple times (about 35)

But **this was not reproduced locally**. Since we only change the server version to H2 the actual behavior is just same as the H1 (both transport and application level). This test might be failed due to some unexpected timeout like a minute which may be caused with some other failing test. Also this test intermittent failure was reported earlier and fixed via https://github.com/ballerina-platform/module-ballerina-http/pull/641

**Comment by chamil321** [comment] 2022-07-14 04:41
> This was experienced when running the tests in locally after defaulting the HTTP server version to H2.
> 
> Tried to reproduce it locally,
> 
> 1. by running `testCircuitBreakerWithoutStatusCodes` test in a loop for multiple times (about 100)
> 2. by running some sub set of CB tests with `testCircuitBreakerWithoutStatusCodes` test in a loop for multiple times (about 50)
> 3. by running all the tests for multiple times (about 35)
> 
> But **this was not reproduced locally**. Since we only change the server version to H2 the actual behavior is just same as the H1 (both transport and application level). This test might be failed due to some unexpected timeout like a minute which may be caused with some other failing test. Also this test intermittent failure was reported earlier and fixed via [ballerina-platform/module-ballerina-http#641](https://github.com/ballerina-platform/module-ballerina-http/pull/641)

Closing as it is not reproducible

**Closed by chamil321** 2022-07-14 04:41 UTC
Labels: Type/Bug, module/http, Team/PCM, http2
