### ISSUE TITLE
DB query does not immediately return if the connection is broken

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#1156] opened 2021-03-23 14:56 UTC
**Description:**
Tested mysql db query when the db is down. the error is not returned immediately

```
Connection is not available, request timed out after 30000ms..* Closing connection 0
```

**Steps to reproduce:**
```ballerina
    resource function get pet/[string id]() returns http:Ok|http:InternalServerError {
        string selectQuery = "Select * from " + tableName + " WHERE ID='" + id + "'";
        stream<record { }, error> resultStream = mysqlClient->query(selectQuery);

        record {| record { } value; |}|error? result = resultStream.next();

        if (result is record {| record { } value; |}) {
            http:Ok res =  {body: result.value.toJson()};
            return res;
        } else if (result is error) {
            http:InternalServerError err = {body: "retrieval failed: " + result.message()};
            return err;
        } else {
            http:Ok err = {body: "No entry for the id: " + id};
            return err;
        }
    }
```
break the db connection and invoke this resource

**Comment by niveathika** [comment] 2021-03-23 16:08
@chamil321 This is the expected behaviour. The default timeout for a connection is 30s. If you want to change you can in the options config.

**Comment by daneshk** [comment] 2021-04-05 08:33
Closing this issue, because it is the expected behavior.

**Closed by daneshk** 2021-04-05 08:33 UTC
Labels: Type/Bug, Version/SLAlpha3, module/mysql
