### ISSUE TITLE
Timeout issue when using kafka producer to publish events to Azure Event hub

### ISSUE THREAD

**Issue by ruwiniwj** [ballerina-platform/ballerina-standard-library#240] opened 2020-10-22 05:58 UTC
**Description:**
gRPC server implemented using the following message and rpc call fails to send data to an azure event hub using a kafka producer.

```
service AnalyticsService {
  rpc PublishEvent(stream Event) returns (google.protobuf.Empty) {}
}

message Event {
    string nodeId = 1;
    string applicationConsumerKey = 2;
    string applicationName = 3;
    string applicationId = 4;
    string applicationOwner = 5;
    string apiContext = 6;
    string apiName = 7;
    string apiVersion = 8;
    string apiResourcePath = 9;
    string apiResourceTemplate = 10;
    string apiMethod = 11;
    string apiCreator = 12;
    string apiCreatorTenantDomain = 13;
    string apiTier = 14;
    string apiHostname = 15;
    string username = 16;
    string userTenantDomain = 17;
    string userIp = 18;
    string userAgent = 19;
    string requestTimestamp  = 20;
    bool throttledOut = 21;
    int64 responseTime = 22;
    int64 serviceTime  = 23;
    int64 backendTime = 24;
    bool responseCacheHit = 25;
    int64 responseSize = 26;
    string protocol = 27;
    int32 responseCode = 28;
    string destination = 29;
    int64 securityLatency = 30;
    int64 throttlingLatency = 31;
    int64 requestMedLat = 32;
    int64 responseMedLat = 33;
    int64 backendLatency = 34;
    int64 otherLatency = 35;
    string gatewayType = 36;
    string label = 37;
    string subscriber = 38;
    string throttledOutReason = 39;
    string throttledOutTimestamp = 40;
    string errorCode = 41;
    string errorMessage = 42;
    string regionId = 43;
    string apiUUID = 44;
    string customerID = 45;
}

```
```
kafka:Producer kafkaProducer = createKafkaProducer();

kafka:AuthenticationConfiguration authConfig = {
    mechanism: kafka:AUTH_SASL_PLAIN,
    username: "$ConnectionString",
    password: eventHubConnectionString
};

map<string> additionalProperties = {
    "metadata.max.idle.ms": "180000",
    "delivery.timeout.ms": "181500"
};

kafka:ProducerConfiguration producerConfigs = {
    bootstrapServers: io:sprintf("%s.servicebus.windows.net:9093", eventHubNamespace),
    valueSerializerType: kafka:SER_BYTE_ARRAY,
    authenticationConfiguration: authConfig,
    batchSize: 1000000,
    lingerInMillis: 500,
    acks: kafka:ACKS_ALL,
    retryCount: 3,
    requestTimeoutInMillis: 60000,
    metadataMaxAgeInMillis: 180000,
    maxInFlightRequestsPerConnection: 1,
    connectionsMaxIdleTimeInMillis: 180000,
    additionalProperties: additionalProperties
};

function createKafkaProducer() returns kafka:Producer {
    return new kafka:Producer(producerConfigs);
}

```

```
resource function PublishEvent(grpc:Caller caller, stream<Event,error> clientStream) {
   error? e = clientStream.forEach(function(Event event) {
      error? x = kafkaProducer->send(getJsonEventString(event).toBytes(), eventHub);
   }
});
```

The gRPC server receives the event, but it fails to publish the event to an Azure Event Hub giving the following error.

` error("Failed to send data to Kafka server: Topic grpc-bal not present in metadata after 60000 ms.")`

However, this scenario can be successfully implement with ballerina 1.2.8 and slp3. 

**Suggested Assignees:**
@aashikam 

**Affected Product Version:**
Ballerina slp4

**Steps to reproduce:**
1. Create an azure event hub
2. Publish data to the event hub using a gRPC server via a kafka producer

**Comment by dilanSachi** [comment] 2021-06-11 10:02
For the producer configuration, you have to add `securityProtocol: kafka:PROTOCOL_SASL_SSL` along with `auth` configuration as default `securityProtocol` in Kafka is `PLAINTEXT`.
```
kafka:ProducerConfiguration producerConfigs = {
    auth: authConfig,
    securityProtocol: kafka:PROTOCOL_SASL_SSL
};
```
Since this issue is not reproduced in swan lake beta 1 with these configurations, we can close this issue.

**Closed** 2021-06-11 10:55 UTC
Labels: Points/2, Priority/High, Team/PCP, Type/Bug, module/kafka
