### ISSUE TITLE
JDBC Client exposes java stacktraces when not having permission to create DB file

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-standard-library#2385] opened 2021-11-11 19:53 UTC
**Description:**

$subject for h2 DB

**Steps to reproduce:**

1. Create a folder in your system with read only permissions. (In my example it is `dbdir`)

tree
.
├── dbdir
└── test.bal

1 directory, 1 file

2. Copy the sample code to test.bal file and run

```ballerina
import ballerinax/java.jdbc;

public function main() returns error? {
    // Initializes the JDBC client.
    jdbc:Client jdbcClient = check new ("jdbc:h2:file:./dbdir/bbes/java_jdbc",
        "rootUser", "rootPass");
    check jdbcClient.close();
}
```

3. Java stacktraces as follows are displayed.

```
bal run test.bal
Compiling source
        test.bal

Running executable

org.h2.message.DbException: Log file error: "/Volumes/work/testBal/dbdir/bbes/java_jdbc.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/Volumes/work/testBal/dbdir/bbes"" [90062-199]" [90034-199]
org.h2.message.DbException: Log file error: "/Volumes/work/testBal/dbdir/bbes/java_jdbc.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/Volumes/work/testBal/dbdir/bbes"" [90062-199]" [90034-199]
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.message.TraceSystem.logWritingError(TraceSystem.java:289)
        at org.h2.message.TraceSystem.openWriter(TraceSystem.java:310)
        at org.h2.message.TraceSystem.writeFile(TraceSystem.java:258)
        at org.h2.message.TraceSystem.write(TraceSystem.java:242)
        at org.h2.message.Trace.error(Trace.java:194)
        at org.h2.engine.Database.openDatabase(Database.java:337)
        at org.h2.engine.Database.<init>(Database.java:313)
        at org.h2.engine.Engine.openSession(Engine.java:69)
        at org.h2.engine.Engine.openSession(Engine.java:201)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
        at org.h2.engine.Engine.createSession(Engine.java:161)
        at org.h2.engine.Engine.createSession(Engine.java:31)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
        at org.h2.Driver.connect(Driver.java:69)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at io.ballerina.stdlib.sql.datasource.SQLDatasource.buildNonXADataSource(SQLDatasource.java:348)
        at io.ballerina.stdlib.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:81)
        at io.ballerina.stdlib.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:232)
        at io.ballerina.stdlib.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:151)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at io.ballerina.stdlib.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:150)
        at io.ballerina.stdlib.sql.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:64)
        at io.ballerina.stdlib.java.jdbc.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:98)
        at ballerinax.java$0046jdbc.1.client.createClient(client.bal:155)
        at ballerinax.java$0046jdbc.1.$value$Client.init(client.bal:43)
        at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
        at ballerinax.java$0046jdbc.1.$value$Client.$init$(client.bal:22)
        at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
        at test.main(test.bal:5)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:323)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Log file error: "/Volumes/work/testBal/dbdir/bbes/java_jdbc.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/Volumes/work/testBal/dbdir/bbes"" [90062-199]" [90034-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        ... 43 more
Caused by: org.h2.message.DbException: Error while creating file "/Volumes/work/testBal/dbdir/bbes" [90062-199]
        at org.h2.message.DbException.get(DbException.java:205)
        at org.h2.message.DbException.get(DbException.java:181)
        at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:290)
        at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43)
        at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:315)
        at org.h2.message.TraceSystem.openWriter(TraceSystem.java:300)
        ... 40 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error while creating file "/Volumes/work/testBal/dbdir/bbes" [90062-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        ... 46 more
error: Error in SQL connector configuration: Failed to initialize pool: Error while creating file "/Volumes/work/testBal/dbdir/bbes" [90062-199] Caused by :Error while creating file "/Volumes/work/testBal/dbdir/bbes" [90062-199]
```
**Affected Versions:**

Ballerina Swan Lake Beta 3
Language specification 2021R1
Update Tool 1.3.6

**Comment by niveathika** [comment] 2021-11-22 14:54
The exception stack trace is printed by the driver itself. The error object only contains the following,
```
error: Error in SQL connector configuration: Failed to initialize pool: Error while creating file "/Volumes/work/testBal/dbdir/bbes" [90062-199] Caused by :Error while creating file "/Volumes/work/testBal/dbdir/bbes" [90062-199]
```

I am looking into disabling logs from third party jars.

**Comment by niveathika** [comment] 2021-11-30 07:22
@anupama-pathirage 

As H2 is an in-memory database, all error messages until the DB is created are printed in System.out of the first connection.

We cannot disable this.

**Comment by daneshk** [comment] 2021-11-30 07:50
Seems like the issue is in the H2 database driver code[1], where they are writing the error stack trace directly to the console. 
So we can't avoid it at connector level.

1. https://github.com/h2database/h2database/blob/master/h2/src/main/org/h2/message/TraceSystem.java#L289-L300

**Comment by daneshk** [comment] 2021-11-30 08:48
I am closing the issue based on the above comments. We have to leave this as a known issue with the h2 database.

**Closed by daneshk** 2021-11-30 08:48 UTC
Labels: Points/0.5, Type/Bug, module/java.jdbc, Team/DIU
