### ISSUE TITLE
In `ballerina/time` in `time:utcFromString` the example is wrong

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-standard-library#2593] opened 2022-01-18 08:19 UTC
**Description:**
$title

Given example is `2007-12-0310:15:30.00Z` and it must be corrected as `2007-12-03T10:15:30.00Z`

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment] 2022-01-21 05:46
I think we fixed this recently. @BuddhiWathsala can you check

**Comment by BuddhiWathsala** [comment] 2022-01-21 06:14
Duplicate of https://github.com/ballerina-platform/ballerina-standard-library/issues/2494

Fixed in https://github.com/ballerina-platform/module-ballerina-time/pull/362

**Closed by BuddhiWathsala** 2022-01-21 06:14 UTC
Labels: Type/Bug, module/time, Team/DIU
