### ISSUE TITLE
HTTP DELETE with payload giving an error (for HTTP2) 

### ISSUE THREAD

**Issue by nadheesh** [ballerina-platform/ballerina-standard-library#4220] opened 2023-03-17 05:17 UTC
**Description:**

```bal
string serviceURL = "https://choreo-chatbot.weaviate.network/v1";

    weaviate:Client wclient = check new (config, serviceUrl=serviceURL);

    http:Client cl = check new(serviceURL);

    json payload = {
    "match": {
        "class": "ChoreoDoc",
        "where": {
            "operator": "GreaterThan",
            "path": [
                "count"
            ],
            "valueNumber": 4.0
        }
    },
    "dryRun": true
    };

    // http:Request request = new;
    // json jsonBody = check payload.cloneWithType(json);
    // request.setPayload(jsonBody, "application/json");

    http:Response rs = check cl->delete("/batch/objects", payload);
    io:println(rs.getJsonPayload());
```

With the above call, I get an error. However, when I try to do a curl, it is working
Error response: 
```
{"code":602,"message":"body in body is required"}
```

With the curl I get following successful response 
```
{
    "dryRun": true,
    "match": {
        "class": "ChoreoDoc",
        "where": {
            "operands": null,
            "operator": "GreaterThan",
            "path": [
                "count"
            ],
            "valueNumber": 4
        }
    },
    "output": "minimal",
    "results": {
        "failed": 0,
        "limit": 100000,
        "matches": 10,
        "objects": null,
        "successful": 0
    }
}
```

**Comment by TharmiganK** [comment] 2023-03-17 05:22
This is giving the expected response if we change the client to HTTP/1.1. Also the curl request is giving the expected response with the upgrade header. So ideally this should work with a ballerina http client.

**Comment by dilanSachi** [comment] 2023-03-21 06:09
We can reproduce this in http1.1 as well by sending the request without a payload. Looks like the payload is not being sent to the server when using http2.

**Comment by shafreenAnfar** [comment] 2023-03-21 16:45
I think https://github.com/ballerina-platform/ballerina-standard-library/issues/3561 could be related to this.

**Comment by TharmiganK** [comment] 2023-03-21 16:55
@dilanSachi can we enable trace logs and check?

**Comment by dilanSachi** [comment] 2023-03-23 10:18
The issue here is that the backend server expects a `Content-Length` header when we are sending the request. However, in `http2` scenario, sending a `Content-Length` header is not mandatory because the receiver can identify whether the content is complete by the `end stream` frame. Here, the issue is with the server as it should identify the end of content using the `end stream` frame rather than relying on the `Content-Length` header.

To resolve this, we can add the `Content-Length` header in our implementation but this would make the internal state machine to store the complete payload in memory to calculate the content size before sending to the server. This would be a unnecessary change as we feel and therefore its better if the user can use `http1.1` when communicating with such servers. Also you can manually set a content-length header when sending the request as well.

Hence closing the issue. Please reopen if more discussion is needed.

**Closed by dilanSachi** 2023-03-23 10:18 UTC
Labels: Priority/High, Type/Bug, module/http, Team/PCM, http2

**Comment by dilanSachi** [comment] 2023-03-23 10:21
A discussion related to this can be found here - https://stackoverflow.com/questions/73361636/content-length-header-in-http-2-for-post-put-request-with-empty-body-required#:~:text=For%20HTTP%2F2%2C%20the%20Content,the%20end%20of%20the%20content.
