### ISSUE TITLE
GraphiQL Schema is not Generated when the Service has `default values`

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#2897] opened 2022-05-11 05:01 UTC
**Description:**
GraphiQL schema is not generated for services that include default values in their fields.
Consider the following service:
```ballerina
import ballerina/graphql;

@graphql:ServiceConfig{
    graphiql: {
        enable: true
    }
}
service /graphql on new graphql:Listener(4000) {
    resource function get name(int id = 3) returns string {
        if id < 5 {
            return "ballerina";
        }
        return "GraphQL";
    }
}
```
GraphiQL Client returns the following error message for this service.
![Screenshot from 2022-05-11 10-26-35](https://user-images.githubusercontent.com/35717653/167772192-0480b8fc-5144-4b21-9e39-e0f2828b20ea.png)

**Comment by ThisaruGuruge** [comment] 2022-05-12 07:45
This seems like an issue from the GraphiQL implementation. Created an issue to get help from them. 
https://github.com/graphql/graphiql/issues/2399

**Comment by ThisaruGuruge** [comment] 2022-06-06 09:05
Closing this since this is not a bug in the Ballerina GraphQL package.

**Comment by ThisaruGuruge** [comment] 2022-08-17 10:00
Closing this since the issue is definitely not in the Ballerina GraphQL package, but in the GraphiQL client where it does not parse an empty string value correctly.

**Comment by ThisaruGuruge** [comment] 2022-08-17 13:31
Re-opening as per https://github.com/graphql/graphiql/issues/2399#issuecomment-1217954478

**Closed** 2022-08-17 14:01 UTC
Labels: Points/0.25, Type/Bug, module/graphql, Team/PCM, Reason/EngineeringMistake
