### ISSUE TITLE
`kafka:Service` should preseve the order of the received messages to `onConsumerRecord` method

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#1662] opened 2021-07-16 05:25 UTC
**Description:**
* In current `kafka:Service` implementation it is doubtful about the order of received messages for `onConsumerRecord` method. Let's assume that kafka is producing four messages 1, 2, 3, 4. In this scenario `onConsumerRecord` method should receive the messages in the same order as they have been produced (meaning  messages should be received in 1,2,3,4 order).

**Comment by dilanSachi** [comment] 2021-07-27 12:18
@aashikam duplicate of https://github.com/ballerina-platform/ballerina-standard-library/issues/1698?

**Comment by aashikam** [comment] 2021-07-28 04:15
@dilanSachi 
issue is fixed in https://github.com/ballerina-platform/module-ballerinax-kafka/pull/254

**Closed by aashikam** 2021-07-28 04:15 UTC
Labels: Team/PCP, Type/Bug, module/kafka
