### ISSUE TITLE
Processing streams in database operations are bit confusing

### ISSUE THREAD

**Issue by lahirusamith** [ballerina-platform/ballerina-standard-library#1445] opened 2021-06-10 06:24 UTC
**Description:**
When we are looking at the [BBE](https://ballerina.io/learn/by-example/jdbc-query-operation) of java.jdbc simple query, it is found that processing streams of that example is bit confusing to a lot of people. 

**Describe your problem(s)**

As in the BBE, 

Ballerina user can give the `Customer` record as expected record type of the stream but yet user can not get that stream directly.   Ballerina developer has to cast the returned stream to expected stream in the second step. 

```ballerina
stream<record{}, error> resultStream =
        jdbcClient->query(`SELECT * FROM Customers`, Customer);

stream<Customer, sql:Error> customerStream =
        <stream<Customer, sql:Error>>resultStream;
```

Also, some may find that, the type received when calling the `resultStream.next();`, is a bit confusing one. 

```ballerina
stream<record{}, error> resultStream =
            jdbcClient->query(`SELECT COUNT(*) AS total FROM Customers`);

record {|record {} value;|}|error? result = resultStream.next();

    if result is record {|record {} value;|} {
        io:println("Total rows in customer table : ", result.value["TOTAL"]);
} 
```

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**
module/sql
module/java.jdbc
module/mysql

**Suggested Assignees (optional):**
Danesh Kuruppu
Lahiru Malepathirana

**Comment by daneshk** [comment] 2021-06-14 04:02
The issue is fixed and merged to the master branch. will be available in beta.2 release. Hence closing the issue.

**Closed by daneshk** 2021-06-14 04:02 UTC
Labels: Team/DIU, Type/Improvement, module/java.jdbc, module/mysql, module/sql
